import {useEffect,useRef,useState} from 'react';
import {Aperture,ArrowRight,ArrowUpRight,BookOpen,BriefcaseBusiness,Camera,Check,ChevronDown,Clock3,Download,FileText,Menu,Search,ShieldBan,Users,X} from 'lucide-react';
import data from '../public/photographer.json';
import {matches,segments} from './search.mjs';
import {Situations,Quiz} from './ShiftTools';

type Card={id:string;title:string;source:string[];blocks:string[];category?:string};
const icons={duties:BriefcaseBusiness,prohibited:ShieldBan,standards:Camera,interaction:Users};
function Highlight({text,query}:{text:string;query:string}){return <>{segments(text,query).map((s:{text:string;match:boolean},i:number)=>s.match?<mark key={i}>{s.text}</mark>:<span key={i}>{s.text}</span>)}</>}
export default function App(){
 const [query,setQuery]=useState('');const [expanded,setExpanded]=useState<Set<string>>(()=>new Set(['rule-6-1','rule-6-2']));const [active,setActive]=useState('duties');const [menu,setMenu]=useState(false);const input=useRef<HTMLInputElement>(null);const drawer=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const dialog=drawer.current;if(!dialog)return;if(menu&&!dialog.open)dialog.showModal();else if(!menu&&dialog.open)dialog.close();},[menu]);
 const searching=!!query.trim();const shown=data.cards.filter(c=>matches(c,query));const mainVisible=matches(data.mainRule,query);const resultCount=shown.length+(mainVisible?1:0);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();input.current?.focus();}if(e.key==='Escape'){setMenu(false);if(document.activeElement===input.current)setQuery('');}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]);
 function jump(id:string,cardId?:string){setQuery('');setActive(id);setMenu(false);if(cardId)setExpanded(s=>new Set([...s,cardId]));requestAnimationFrame(()=>{const target=document.getElementById(cardId??id);target?.focus({preventScroll:true});target?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});});}
 function toggle(id:string){setExpanded(s=>{const next=new Set(s);next.has(id)?next.delete(id):next.add(id);return next})}
 const navigation=<><div className="nav-label">В ЭТОМ РЕГЛАМЕНТЕ</div>{data.categories.map((c,i)=>{const Icon=icons[c.id as keyof typeof icons];return <button key={c.id} className={'nav-item '+(active===c.id&&!searching?'selected':'')} onClick={()=>jump(c.id)}><Icon size={19}/><span>{c.title}</span><small>{String(i+1).padStart(2,'0')}</small></button>})}</>;
 return <div className="app-shell"><a className="skip-link" href="#main">К регламенту</a>
 <aside className="sidebar"><a className="brand" href="#main" aria-label="PHOTO LAB — начало"><img src="/photolab-logo.png" alt="ФОТОЛАБ — ваши фотографии с любовью"/></a><div className="sidebar-divider"/><div className="workspace-label"><BookOpen size={16}/> Корпоративная книга</div><div className="role-card"><span className="role-icon"><Camera size={22}/></span><div><small>ВАША РОЛЬ</small><strong>{data.role}</strong></div><Check size={16}/></div><nav aria-label="Разделы регламента">{navigation}</nav><div className="sidebar-bottom"><div className="edition"><span/> Раздел 06 / Фотограф</div><p>Правила под рукой.<br/>В любой момент смены.</p><div className="prototype-note"><FileText size={14}/> Демонстрационный прототип</div></div></aside>
 <dialog ref={drawer} aria-label="Разделы регламента" className="mobile-overlay" onClose={()=>setMenu(false)} onCancel={()=>setMenu(false)} onClick={()=>setMenu(false)}><nav className="mobile-menu" aria-label="Мобильная навигация" onClick={e=>e.stopPropagation()}><div className="mobile-menu-top"><img className="mobile-logo" src="/photolab-logo.png" alt="ФОТОЛАБ"/><button className="icon-button" autoFocus aria-label="Закрыть меню" onClick={()=>setMenu(false)}><X/></button></div>{navigation}</nav></dialog>
 <div className="page"><header className="topbar"><div className="breadcrumbs"><button className="icon-button mobile-menu-button" aria-label="Открыть меню" aria-expanded={menu} onClick={()=>setMenu(true)}><Menu size={22}/></button><BookOpen size={16}/><span>База знаний</span><span className="crumb-slash">/</span><strong>Фотограф</strong></div><span className="demo-badge"><span/> Прототип</span></header>
 <main id="main"><section className="hero"><div className="eyebrow"><span className="chapter-tag">06</span> КОРПОРАТИВНАЯ КНИГА <span className="eyebrow-line"/></div><div className="hero-heading"><div><h1>Регламент<br/><span>фотографа</span><span className="title-dot">.</span></h1><p className="hero-description">{data.intro}</p></div><div className="hero-symbol" aria-hidden="true"><span className="lens-ring"/><span className="lens-label">В ФОКУСЕ<br/>КАЖДАЯ СМЕНА</span></div></div><div className="hero-meta"><span><FileText size={15}/> 10 пунктов регламента</span><span><Clock3 size={15}/> ≈ 5 минут чтения</span></div></section>
 <div className="search-sticky"><div className="search-box"><Search size={22}/><label className="sr-only" htmlFor="rule-search">Поиск по всему регламенту</label><input id="rule-search" ref={input} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск по тексту регламента…" autoComplete="off"/>{query?<button className="icon-button" aria-label="Очистить поиск" onClick={()=>{setQuery('');input.current?.focus()}}><X size={19}/></button>:<kbd>⌘ / Ctrl K</kbd>}</div>{!searching&&<div className="quick-queries"><span>Например:</span>{['брак','телефон','родители'].map(word=><button key={word} onClick={()=>{setQuery(word);input.current?.focus()}}>{word}<ArrowUpRight size={12}/></button>)}</div>}</div>
 {!searching&&<><div className="section-kicker"><span>БЫСТРАЯ ПАМЯТКА</span><span>Три ориентира на смену</span></div><section className="facts" aria-label="Быстрая памятка">{data.quickFacts.map((f,i)=><button key={f.label} className="fact" onClick={()=>jump(i===2?'interaction':'standards',f.target)}><div className="fact-top"><span className="fact-number">{f.value}<small>{f.unit}</small></span><ArrowUpRight size={19}/></div><strong>{f.label}</strong><p>{f.detail}</p></button>)}</section></>}
 {!searching&&<Situations onSource={jump}/>}
 <div className="content-toolbar"><div>{searching?<><h2>Результаты поиска</h2><p role="status" aria-live="polite">Найдено карточек: {resultCount}</p></>:<><h2>Все правила</h2><p>Выберите раздел или раскройте нужный пункт</p></>}</div>{!searching&&<button className="text-button" onClick={()=>setExpanded(s=>s.size===data.cards.length?new Set():new Set(data.cards.map(c=>c.id)))}>{expanded.size===data.cards.length?'Свернуть всё':'Раскрыть всё'}<ChevronDown size={16}/></button>}</div>
 {searching&&resultCount===0?<div className="empty-state"><Search size={32}/><h3>Ничего не нашлось</h3><p>Попробуйте другое слово или более короткий запрос.</p><button className="primary-button" onClick={()=>{setQuery('');input.current?.focus()}}>Показать все правила <ArrowRight size={17}/></button></div>:data.categories.map((category,index)=>{const cards=shown.filter(c=>c.category===category.id);if(!cards.length)return null;const Icon=icons[category.id as keyof typeof icons];return <section className={'rule-section '+category.id} id={category.id} tabIndex={-1} key={category.id}><div className="category-header"><span className="category-icon"><Icon size={20}/></span><div><h3>{category.title}<span>{cards.length}</span></h3><p>{category.description}</p></div><span className="section-index">0{index+1}</span></div><div className="cards">{cards.map(card=><RuleCard key={card.id} card={card} query={query} open={searching||expanded.has(card.id)} onToggle={()=>toggle(card.id)} forced={searching}/>)}</div></section>})}
 {mainVisible&&<section className="main-rule" id="main-rule"><div className="main-rule-label"><Aperture size={20}/><span>{data.mainRule.title}</span><small>§ 6.10</small></div><p>«<Highlight text={data.mainRule.blocks[0]} query={query}/>»</p><span className="main-rule-decor" aria-hidden="true">↗</span></section>}
 {!searching&&<Quiz onSource={jump}/>}
 <footer><div><span className="footer-brand">PHOTO LAB</span><span>Корпоративная книга · Раздел 6</span></div><a href="/photographer.json" download><Download size={15}/> Скачать регламент JSON</a></footer>
 </main></div></div>
}
function RuleCard({card,query,open,onToggle,forced}:{card:Card;query:string;open:boolean;onToggle:()=>void;forced:boolean}){return <article className={'rule-card '+(open?'is-open':'')} id={card.id} tabIndex={-1}><h4><button className="card-toggle" aria-expanded={open} aria-controls={card.id+'-content'} onClick={onToggle} disabled={forced}><span className="source-number">{card.source.map(s=><Highlight key={s} text={s} query={query}/>)}</span><span className="card-title"><Highlight text={card.title} query={query}/></span><ChevronDown size={18}/></button></h4><div id={card.id+'-content'} hidden={!open} className="card-content">{card.blocks.map((block,i)=><p key={i}><Highlight text={block} query={query}/></p>)}</div></article>}
