import {useRef,useState} from 'react';
import {ArrowRight,ArrowUpRight,Check,ChevronDown,RotateCcw,Zap} from 'lucide-react';
import {questions,situations} from './training';
type Props={onSource:(category:string,id:string)=>void};
export function Situations({onSource}:Props){
 const [selected,setSelected]=useState<string|null>(null);
 return <section className="situations" aria-labelledby="situations-title"><div className="tool-heading"><div><span className="overline">ПОМОЩЬ НА СМЕНЕ</span><h2 id="situations-title">Что случилось?</h2></div><Zap size={22} aria-hidden="true"/></div><p className="tool-description">Выберите ситуацию — нужное правило уже рядом.</p><div className="situation-grid">{situations.map((s,i)=><div className={'situation '+(selected===s.id?'active':'')} key={s.id}><h3><button aria-expanded={selected===s.id} aria-controls={'answer-'+s.id} onClick={()=>setSelected(selected===s.id?null:s.id)}><span className="situation-number">0{i+1}</span><span><strong>{s.title}</strong><small>{s.hint}</small></span><ChevronDown size={17}/></button></h3><div id={'answer-'+s.id} hidden={selected!==s.id} className="situation-answer"><p>{s.answer}</p><div className="source-links">{s.sources.map(source=><button key={source} onClick={()=>onSource(s.category,'rule-'+source.replace('.','-'))}>Открыть § {source}<ArrowUpRight size={15}/></button>)}</div></div></div>)}</div><p className="source-caption">Короткие ответы по главе 6. Полный текст — в регламенте ниже.</p></section>
}
export function Quiz({onSource}:Props){
 const [started,setStarted]=useState(false);const [answers,setAnswers]=useState<number[]>([]);const [step,setStep]=useState(0);const heading=useRef<HTMLHeadingElement>(null);
 const done=step===questions.length;const question=questions[step];const answered=answers[step]!==undefined;const score=answers.reduce((sum,a,i)=>sum+Number(a===questions[i].correct),0);
 function focusHeading(){requestAnimationFrame(()=>heading.current?.focus({preventScroll:true}));}
 return <section className="quiz" aria-labelledby="quiz-title"><div className="quiz-intro"><span className="overline">ПЕРЕД ПЕРВОЙ СМЕНОЙ</span><h2 id="quiz-title" ref={heading} tabIndex={-1}>{done?'Проверка завершена':started?'Проверим на практике':'Готовы к смене?'}</h2><p>{done?`Ваш результат: ${score} из ${questions.length}. ${score===5?'Все ситуации разобраны.':'Ошибки — повод ещё раз открыть нужные пункты.'}`:started?'Выберите один ответ. После него — объяснение и пункт регламента.':'Пять рабочих ситуаций, чтобы проверить себя. Около двух минут, без оценок руководителю.'}</p></div>{!started?<button className="primary-button" onClick={()=>{setStarted(true);focusHeading()}}>Проверить себя<ArrowRight size={17}/></button>:done?<div className="quiz-result"><div className="quiz-review">{questions.map((q,i)=><div key={q.source+i}><span className={answers[i]===q.correct?'result-good':'result-retry'}>{answers[i]===q.correct?'Верно':'Повторить'}</span><p>{q.prompt}</p><button onClick={()=>onSource(q.category,'rule-'+q.source.replace('.','-'))}>§ {q.source}<ArrowUpRight size={14}/></button></div>)}</div><button className="text-button" onClick={()=>{setAnswers([]);setStep(0);focusHeading()}}><RotateCcw size={16}/>Пройти ещё раз</button></div>:<div className="quiz-body"><div className="quiz-progress"><span>Вопрос {step+1} / {questions.length}</span><div aria-hidden="true">{questions.map((_,i)=><span key={i} className={i<=step?'filled':''}/>)}</div></div><h3>{question.prompt}</h3><div className="quiz-options">{question.options.map((option,i)=><button key={option} disabled={answered} className={answered?(i===question.correct?'correct':answers[step]===i?'incorrect':''):''} onClick={()=>setAnswers([...answers,i])}><span>{String.fromCharCode(65+i)}</span>{option}{answered&&i===question.correct&&<Check size={18}/>}</button>)}</div>{answered&&<div className="quiz-feedback" role="status"><strong>{answers[step]===question.correct?'Верно.':'Разберём ответ.'}</strong><p>{question.explanation}</p><div><button className="text-button" onClick={()=>onSource(question.category,'rule-'+question.source.replace('.','-'))}>Читать § {question.source}<ArrowUpRight size={15}/></button><button className="primary-button" onClick={()=>{setStep(step+1);focusHeading()}}>{step===4?'Показать результат':'Следующий вопрос'}<ArrowRight size={16}/></button></div></div>}</div>}</section>
}
